### PR TITLE
Add possible fix case for #4

### PR DESCRIPTION
**Pull request by fsgonz**

### CODE REVIEW

**Comment by ghost** [comment]
@fsgonz In order to consider accepting the PR, we will need a signed OCA.  Please see [https://github.com/javaee/grizzly-ahc/blob/master/CONTRIBUTING.md](https://github.com/javaee/grizzly-ahc/blob/master/CONTRIBUTING.md)

**Comment by ghost** [comment]
@fsgonz Just a reminder: In order to consider accepting the PR, we will need a signed OCA. Please see https://github.com/javaee/grizzly-ahc/blob/master/CONTRIBUTING.md

Please let me know when this has been submitted.

**Comment by fsgonz** [comment]
@rlubke, I've just submitted the OCA. Thanks

**Comment by delabassee** [comment]
@fsgonz you haven't filled section 7 of the OCA, could you please fix that?

**Comment by fsgonz** [comment]
@delabassee, I've resubmitted the OCA with an x in section 7. My apologies.

**Comment by fsgonz** [comment]
@delabassee @rlubke, let me know if anything else is needed.

**Comment by delabassee** [comment]
@fsgonz You have fixed section 7 but given that it's signed on your own behalf, you shouldn't include a company name! Can you fix that and also clearly write your first/last name (scanned handwriting is a bit challenging).

**Comment by fsgonz** [comment]
@delabassee just sent the oca without company name. Let me know.

**Comment by delabassee** [comment]
@fsgonz @rlubke You OCA is now approved, thanks!

**Comment by fsgonz** [comment]
@delabassee thanks!

**Review by ghost — APPROVED** [review]

**Pull request merged**
